### ISSUE TITLE
npm install failed for the reason  submodule xmlbuilder/lib/XMLStringifier.js:153:15  Invalid character 

### ISSUE THREAD

**Issue by maintiendrai** [bikenik/alfred-ldoce#5]
Hi , nice job

when i install alfred-ldoce@1.2.2 , it works well , but when the version after 1.2.2 cause the Invalid character error 

npm install failed for  submodule xmlbuilder/lib/XMLStringifier.js:153:15  Invalid character 

```
{ Error: Command failed: alfred-link
Error: Invalid character (�) in string: ...
🔦 SEE ALSO at index 4
    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:153:15)
    at XMLStringifier.assertLegalChar (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
    at XMLStringifier.module.exports.XMLStringifier.eleText (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:33:19)
    at new XMLText (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLText.js:17:35)
    at XMLElement.module.exports.XMLNode.text (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
    at XMLElement.module.exports.XMLNode.txt (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLNode.js:365:19)
    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:127:30)
    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)
    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)
    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)


    at Promise.all.then.arr (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Invalid character (�) in string: ...\n🔦 SEE ALSO at index 4\n    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:153:15)\n    at XMLStringifier.assertLegalChar (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)\n    at XMLStringifier.module.exports.XMLStringifier.eleText (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLStringifier.js:33:19)\n    at new XMLText (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLText.js:17:35)\n    at XMLElement.module.exports.XMLNode.text (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLNode.js:165:15)\n    at XMLElement.module.exports.XMLNode.txt (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/xmlbuilder/lib/XMLNode.js:365:19)\n    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:127:30)\n    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)\n    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)\n    at walk_obj (/Users/maintiendrai/.nvm/versions/node/v8.11.2/lib/node_modules/alfred-ldoce/node_modules/plist/lib/build.js:110:9)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
```

**Comment by maintiendrai** [comment]
Amazing quick fix . 
Looking forward to  your Webster Verison.
